const contactContent = {
  en: {
    heading: "Contact",
    headingAccent: "Us",
    namePlaceholder: "Enter your name",
    emailPlaceholder: "Enter your email",
    messagePlaceholder: "Enter your message",
    sendButton: "Send Message",
    sending: "Sending...",
    sent: "Message Sent!",
    brandMessage: "Empowering your ideas with next-gen digital solutions.",
    errorNetwork: "Network or server error. Please try again.",
  },
  ur: {
    heading: "رابطہ",
    headingAccent: "کریں",
    namePlaceholder: "اپنا نام درج کریں",
    emailPlaceholder: "اپنا ای میل درج کریں",
    messagePlaceholder: "اپنا پیغام لکھیں",
    sendButton: "پیغام بھیجیں",
    sending: "...بھیجا جا رہا ہے",
    sent: "پیغام بھیج دیا گیا!",
    brandMessage: "آپ کے خیالات کو جدید ڈیجیٹل سلوشنز کے ساتھ حقیقت بناتے ہیں۔",
    errorNetwork: "نیٹ ورک یا سرور میں مسئلہ ہے۔ دوبارہ کوشش کریں۔",
  },
  ar: {
    heading: "تواصل",
    headingAccent: "معنا",
    namePlaceholder: "أدخل اسمك",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    messagePlaceholder: "اكتب رسالتك",
    sendButton: "إرسال الرسالة",
    sending: "...جاري الإرسال",
    sent: "تم إرسال الرسالة!",
    brandMessage: "نحو مستقبل رقمي وذكاء اصطناعي لأفكارك.",
    errorNetwork: "خطأ في الشبكة أو الخادم. يرجى المحاولة مرة أخرى.",
  },
  zh: {
    heading: "联系我们",
    headingAccent: "",
    namePlaceholder: "请输入您的姓名",
    emailPlaceholder: "请输入您的邮箱",
    messagePlaceholder: "请输入您的留言",
    sendButton: "发送信息",
    sending: "发送中...",
    sent: "信息已发送！",
    brandMessage: "用创新数字方案助力您的每一个想法。",
    errorNetwork: "网络或服务器错误。请再试一次。",
  },
  fr: {
    heading: "Contact",
    headingAccent: "ez-nous",
    namePlaceholder: "Entrez votre nom",
    emailPlaceholder: "Entrez votre email",
    messagePlaceholder: "Entrez votre message",
    sendButton: "Envoyer le message",
    sending: "Envoi...",
    sent: "Message envoyé !",
    brandMessage: "Donnez vie à vos idées avec des solutions digitales innovantes.",
    errorNetwork: "Erreur réseau ou serveur. Veuillez réessayer.",
  },
  de: {
    heading: "Kontakt",
    headingAccent: "aufnehmen",
    namePlaceholder: "Geben Sie Ihren Namen ein",
    emailPlaceholder: "Geben Sie Ihre E-Mail ein",
    messagePlaceholder: "Geben Sie Ihre Nachricht ein",
    sendButton: "Nachricht senden",
    sending: "Wird gesendet...",
    sent: "Nachricht gesendet!",
    brandMessage: "Wir verwirklichen Ihre Ideen mit digitalen Innovationen.",
    errorNetwork: "Netzwerk- oder Serverfehler. Bitte versuchen Sie es erneut.",
  },
  ja: {
    heading: "お問い合わせ",
    headingAccent: "",
    namePlaceholder: "お名前を入力してください",
    emailPlaceholder: "メールアドレスを入力してください",
    messagePlaceholder: "メッセージを入力してください",
    sendButton: "メッセージ送信",
    sending: "送信中...",
    sent: "送信されました！",
    brandMessage: "次世代デジタルソリューションであなたのアイデアを実現します。",
    errorNetwork: "ネットワークまたはサーバーエラーです。もう一度お試しください。",
  },
};

export default contactContent;

export type ContactContent = typeof contactContent["en"];
